# --------------------------------------------------------
#              SimpleCommandDisabler Config
# --------------------------------------------------------

# List of commands you want to block.
# You can enter them with or without the leading '/'
# The check is case-insensitive.
blocked-commands:
  - plugins
  - version
  - pl
  - about
  - ?

# The message displayed to players when they try to use a blocked command.
# Supports color codes (e.g., &c for red, &l for bold).
blocked-message: "&c&lâœ˜ &7I'm sorry, but you cannot use this command!"